const ACTIONS ={
    //FETCH QUESTIONS
    FETCH_QUESTIONS_START:"FETCH_QUESTIONS_START",
    FETCH_QUESTIONS_SUCCESS:"FETCH_QUESTIONS_SUCCESS",
    FETCH_QUESTIONS_ERROR:"FETCH_QUESTIONS_ERROR",
    //FETCH TOP USERS
    FETCH_TOP_USERS_START:"FETCH_TOP_USERS_START",
    FETCH_TOP_USERS_SUCCESS:"FETCH_TOP_USERS_SUCCESS",
    FETCH_TOP_USERS_ERROR:"FETCH_TOP_USERS_ERROR",
}
export default ACTIONS
