const ACTIONS ={
    //FETCH QUESTIONS
    FETCH_QUESTIONS_START:"FETCH_QUESTIONS_START",
    FETCH_QUESTIONS_SUCCESS:"FETCH_QUESTIONS_SUCCESS",
    FETCH_QUESTIONS_ERROR:"FETCH_QUESTIONS_ERROR"
}
export default ACTIONS
